/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const PaymentMethodType1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `30.67px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Cc11 = styled('img')({
  height: `30.67px`,
  width: `48px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function PaymentOptions(props) {
  return (
    <PaymentMethodType1 className={props.className}>
      <Cc11
        src={`assets/images/PaymentOptions_cc_1_1.png`}
        loading="lazy"
        alt={'cc-1 1'}
      />
    </PaymentMethodType1>
  );
}

export default PaymentOptions;
