/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react'
import useShopNavbar1ResponsiveSize from './useShopNavbar1ResponsiveSize'

/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
  ScreenDesktopTypeQuest: 'ScreenDesktopTypeQuest',
  ScreenTabletTypeQuest: 'ScreenTabletTypeQuest',
  ScreenMobileTypeQuest: 'ScreenMobileTypeQuest',
}

const useShopNavbar1 = (props) => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['ScreenDesktopTypeQuest']
  )

  const breakpointsVariant = useShopNavbar1ResponsiveSize()

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant)
    }
  }, [breakpointsVariant])

  const [anchorEl, setAnchorEl] = React.useState(null)

  const handleClick = (event) => {
    setAnchorEl(event.currentTarget)
  }

  const handleClose = () => {
    setAnchorEl(null)
  }

  const open = Boolean(anchorEl)
  const id = open ? 'simple-popover' : undefined
  const data = {
    currentVariant,
    anchorEl,
    open,
    id,
  }

  const fns = { setCurrentVariant, handleClick, handleClose }

  return { data, fns }
}

export default useShopNavbar1
