/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useEffect } from 'react'
import useLayoutProductList1ResponsiveSize from './useLayoutProductList1ResponsiveSize'
import shopify from '../../services/shopify'
/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
  ScreenDesktop: 'ScreenDesktop',
  ScreenTablet: 'ScreenTablet',
  ScreenMobile: 'ScreenMobile',
}

const useLayoutProductList1 = () => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['ScreenDesktop']
  )
  const [products, setProducts] = React.useState([])
  const [product, setProduct] = React.useState(null)
  const breakpointsVariant = useLayoutProductList1ResponsiveSize()

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant)
    }
  }, [breakpointsVariant])

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const products = await shopify.product.fetchAll()
        setProducts(
          JSON.parse(
            JSON.stringify(
              products.sort(
                (a, b) =>
                  +b.variants[0].price.amount - +a.variants[0].price.amount
              )
            )
          )
        )
      } catch (error) {
        alert('Incorrect Shopify Configuration')
      }
    }
    fetchProducts()
  }, [])

  const handleProductClick = (id) => {
    setProduct(id)
  }

  const data = { currentVariant, products, product }

  const fns = {
    setCurrentVariant,
    handleProductClick,
  }

  return { data, fns }
}

export default useLayoutProductList1
